#pragma once

#define IDI_STORYLAND 1
#define IDR_VCS_TIMECYC 101
#define IDR_REIGNS_ERROR_THEME 102
#define IDR_REIGNS_SPLASH_MEME_GIF 103
#define IDR_VCS_ERROR_WARNING_THEME 104
#define IDR_GTA3_ERROR_THEME 105
#define IDR_GTAVC_ERROR_THEME 106
#define IDR_GTASA_ERROR_THEME 107
