#include "storyland_shaders.h"

const char* storylandStoriesVertexShaderSource() {
    return
        "#version 120\n"
        "varying vec4 vColor;\n"
        "varying vec2 vTex0;\n"
        "varying vec3 vLighting;\n"
        "varying float vSpecular;\n"
        "varying float vRim;\n"
        "varying float vFog;\n"
        "uniform vec3 uAmbientColor;\n"
        "uniform vec3 uDirectionalColor;\n"
        "uniform vec3 uSunDirection;\n"
        "uniform float uFogStart;\n"
        "uniform float uFarClip;\n"
        "void main(){\n"
        "  vec4 eyePos = gl_ModelViewMatrix * gl_Vertex;\n"
        "  gl_Position = gl_ModelViewProjectionMatrix * gl_Vertex;\n"
        "  vColor = gl_Color;\n"
        "  vTex0 = gl_MultiTexCoord0.xy;\n"
        "  vec3 n = normalize(gl_NormalMatrix * gl_Normal);\n"
        "  vec3 lightDir = normalize(gl_NormalMatrix * uSunDirection);\n"
        "  vec3 viewDir = normalize(-eyePos.xyz);\n"
        "  float ndl = dot(n, lightDir);\n"
        "  float direct = max(ndl, 0.0);\n"
        "  float halfLambert = ndl * 0.5 + 0.5;\n"
        "  float bounce = max(dot(n, vec3(0.0, 0.0, 1.0)), 0.0) * 0.18;\n"
        "  float backfill = max(dot(n, -lightDir), 0.0) * 0.12;\n"
        "  vLighting = clamp(uAmbientColor + uDirectionalColor * (halfLambert * 0.62 + direct * 0.38 + bounce + backfill), 0.0, 1.45);\n"
        "  vec3 halfVec = normalize(lightDir + viewDir);\n"
        "  vSpecular = pow(max(dot(n, halfVec), 0.0), 20.0) * step(0.0, ndl) * 0.14;\n"
        "  vRim = pow(clamp(1.0 - max(dot(n, viewDir), 0.0), 0.0, 1.0), 2.4) * 0.10;\n"
        "  float distanceFromCamera = length(eyePos.xyz);\n"
        "  float fogRange = max(uFarClip - uFogStart, 0.001);\n"
        "  vFog = clamp((uFarClip - distanceFromCamera) / fogRange, 0.0, 1.0);\n"
        "}\n";
}

const char* storylandStoriesFragmentShaderSource() {
    return
        "#version 120\n"
        "uniform sampler2D tex0;\n"
        "uniform int uUseTexture;\n"
        "uniform int uRenderMode;\n"
        "uniform vec3 uFogColor;\n"
        "uniform vec3 uDirectionalColor;\n"
        "varying vec4 vColor;\n"
        "varying vec2 vTex0;\n"
        "varying vec3 vLighting;\n"
        "varying float vSpecular;\n"
        "varying float vRim;\n"
        "varying float vFog;\n"
        "void main(){\n"
        "  vec4 base = vColor;\n"
        "  if(uUseTexture != 0){\n"
        "    vec4 tex = texture2D(tex0, vTex0);\n"
        "    base *= tex;\n"
        "  }\n"
        "  vec3 lit = base.rgb;\n"
        "  if(uRenderMode == 0 || uRenderMode == 2){\n"
        "    lit = base.rgb * vLighting;\n"
        "    lit += vSpecular * uDirectionalColor;\n"
        "    lit += vRim * mix(base.rgb, uDirectionalColor, 0.35);\n"
        "  }\n"
        "  lit = clamp(lit, 0.0, 1.0);\n"
        "  lit = mix(uFogColor, lit, vFog);\n"
        "  gl_FragColor = vec4(lit, base.a);\n"
        "}\n";
}
